Virtual devices cannot be modified after being initialized
Epoch 1/128
2022-05-27 23:14:08.210594: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8400

























































    125/Unknown - 126s 921ms/step - loss: 0.2233 - accuracy: 0.4090
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    model_history = model.fit(
  File "/home/melih/anaconda3/envs/tf-web/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/melih/Code/uni/sem6/deep_cv/train_unet.py", line 129, in on_epoch_end
    show_predictions()
  File "/home/melih/Code/uni/sem6/deep_cv/train_unet.py", line 147, in show_predictions
    if dataset:

NameError: name 'dataset' is not defined